[[plugins]]
package = "@netlify/plugin-gatsby"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/"
  to = "https://subvisual-redesign.webflow.io/"
  status = 200
  force = true

[[redirects]]
  from = "/services"
  to = "https://subvisual-redesign.webflow.io/services"
  status = 200
  force = true

[[redirects]]
  from = "/academy"
  to = "https://jobs.subvisual.com/academy"

[[redirects]]
  from = "/ventures"
  to = "https://subvisual-redesign.webflow.io/ventures"
  status = 200
  force = true

[[redirects]]
  from = "/people"
  to = "https://subvisual-redesign.webflow.io/people"
  status = 200
  force = true

[[redirects]]
  from = "/brand"
  to = "https://subvisual-redesign.webflow.io/brand"
  status = 200
  force = true

[[redirects]]
  from = "/leads-form"
  to = "https://subvisual-redesign.webflow.io/leads-form"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "https://subvisual-redesign.webflow.io/services"
  status = 200
  force = true

[[redirects]]
  from = "/smarttalks"
  to = "https://subvisual.notion.site/Society-of-Mars-Advanced-Royal-Tech-Talks-28cf36c8beac41c9a9b01046f98b7c6c"

[[redirects]]
  from = "/smartereveryfriday"
  to = "https://subvisual.notion.site/Smarter-Every-Friday-Conspiracy-b72e3389f87c4bac83b48fac2434c89a"
